apiVersion: v1
kind: ConfigMap
metadata:
  name: bookhub-config
data:
  DB_HOST: bookhub-db
  DB_NAME: bookhub

---
apiVersion: v1
kind: Secret
metadata:
  name: bookhub-secret
type: Opaque
stringData:
  DB_USER: root
  DB_PASS: password
